# Site Settings
title: "Elena's CV"
url: 'http://webjeda.com'
baseurl: '/cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Elena <br> <i>Torlai Triglia</i>
tagline: Postdoctoral researcher
pic: pic.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Bioinformatician and molecular biologist. PhD from the Humboldt university of Berlin, currently a postdoc at Ana Pombo's lab at the the Berlin Institute for Medical Systems Biology (part of the Max Delbruck Center for Molecular Medicine). Captivated by multidisciplinary, open research. Interested in gene regulation, epigenetics, single-cell and systems biology. Aiming to improve our understanding of cell states.'

#sidebar links
email: elena.torlai-triglia@mdc-berlin.de
phone: 
website:  #do not add http://
linkedin: elena-torlai-triglia
github: ElenaTT
twitter: '@ele_tt'
scholar: 9-XWIZIAAAAJ
orcid: 0000-0002-6059-0116
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-113953128-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
